export const medicalSpecialties = [
    { label: "Cardiologist", value: "Cardiologist" },
    { label: "Dermatologist", value: "Dermatologist" },
    { label: "Neurologist", value: "Neurologist" },
    { label: "Orthopedic Surgeon", value: "Orthopedic Surgeon" },
    { label: "Pediatrician", value: "Pediatrician" },
    { label: "Psychiatrist", value: "Psychiatrist" },
    { label: "Radiologist", value: "Radiologist" },
    { label: "Oncologist", value: "Oncologist" },
    { label: "Endocrinologist", value: "Endocrinologist" },
    { label: "Gastroenterologist", value: "Gastroenterologist" },
    { label: "Ophthalmologist", value: "Ophthalmologist" },
    { label: "Obstetrician", value: "Obstetrician" },
    { label: "Gynecologist", value: "Gynecologist" },
    { label: "Urologist", value: "Urologist" },
    { label: "Nephrologist", value: "Nephrologist" },
    { label: "Pulmonologist", value: "Pulmonologist" },
    { label: "Rheumatologist", value: "Rheumatologist" },
    { label: "Anesthesiologist", value: "Anesthesiologist" },
    { label: "Otolaryngologist", value: "Otolaryngologist" },
    { label: "Plastic Surgeon", value: "Plastic Surgeon" },
    { label: "Infectious Disease Specialist", value: "Infectious Disease Specialist" },
    { label: "Hematologist", value: "Hematologist" },
    { label: "Allergist", value: "Allergist" },
    { label: "Immunologist", value: "Immunologist" },
    { label: "General Surgeon", value: "General Surgeon" },
    { label: "Thoracic Surgeon", value: "Thoracic Surgeon" },
    { label: "Vascular Surgeon", value: "Vascular Surgeon" },
    { label: "Pathologist", value: "Pathologist" },
    { label: "Podiatrist", value: "Podiatrist" },
    { label: "Geriatrician", value: "Geriatrician" },
    { label: "Pain Management Specialist", value: "Pain Management Specialist" },
    { label: "Emergency Medicine Physician", value: "Emergency Medicine Physician" },
    { label: "Family Medicine Physician", value: "Family Medicine Physician" },
    { label: "Sports Medicine Specialist", value: "Sports Medicine Specialist" },
    { label: "Occupational Medicine Specialist", value: "Occupational Medicine Specialist" },
    { label: "Preventive Medicine Specialist", value: "Preventive Medicine Specialist" },
    { label: "Internal Medicine Physician", value: "Internal Medicine Physician" },
    { label: "Critical Care Medicine Specialist", value: "Critical Care Medicine Specialist" },
    { label: "Nuclear Medicine Specialist", value: "Nuclear Medicine Specialist" },
    { label: "Geneticist", value: "Geneticist" },
    { label: "Pediatric Surgeon", value: "Pediatric Surgeon" },
    { label: "Neonatologist", value: "Neonatologist" },
    { label: "Bariatric Surgeon", value: "Bariatric Surgeon" },
    { label: "Transplant Surgeon", value: "Transplant Surgeon" },
    { label: "Hand Surgeon", value: "Hand Surgeon" },
    { label: "Colorectal Surgeon", value: "Colorectal Surgeon" },
    { label: "Sleep Medicine Specialist", value: "Sleep Medicine Specialist" },
    { label: "Hospitalist", value: "Hospitalist" },
    { label: "Medical Oncologist", value: "Medical Oncologist" },
    { label: "Surgical Oncologist", value: "Surgical Oncologist" },
    { label: "Radiation Oncologist", value: "Radiation Oncologist" }
];

export const medications = [
    { label: "Aspirin", value: "Aspirin" },
    { label: "Ibuprofen", value: "Ibuprofen" },
    { label: "Acetaminophen", value: "Acetaminophen" },
    { label: "Amoxicillin", value: "Amoxicillin" },
    { label: "Metformin", value: "Metformin" },
    { label: "Atorvastatin", value: "Atorvastatin" },
    { label: "Lisinopril", value: "Lisinopril" },
    { label: "Albuterol", value: "Albuterol" },
    { label: "Omeprazole", value: "Omeprazole" },
    { label: "Levothyroxine", value: "Levothyroxine" },
    { label: "Metoprolol", value: "Metoprolol" },
    { label: "Amlodipine", value: "Amlodipine" },
    { label: "Simvastatin", value: "Simvastatin" },
    { label: "Hydrochlorothiazide", value: "Hydrochlorothiazide" },
    { label: "Losartan", value: "Losartan" },
    { label: "Gabapentin", value: "Gabapentin" },
    { label: "Sertraline", value: "Sertraline" },
    { label: "Fluticasone", value: "Fluticasone" },
    { label: "Prednisone", value: "Prednisone" },
    { label: "Furosemide", value: "Furosemide" },
    { label: "Montelukast", value: "Montelukast" },
    { label: "Clopidogrel", value: "Clopidogrel" },
    { label: "Warfarin", value: "Warfarin" },
    { label: "Tramadol", value: "Tramadol" },
    { label: "Trazodone", value: "Trazodone" },
    { label: "Meloxicam", value: "Meloxicam" },
    { label: "Cetirizine", value: "Cetirizine" },
    { label: "Loratadine", value: "Loratadine" },
    { label: "Diphenhydramine", value: "Diphenhydramine" },
    { label: "Zolpidem", value: "Zolpidem" },
    { label: "Ranitidine", value: "Ranitidine" },
    { label: "Famotidine", value: "Famotidine" },
    { label: "Doxycycline", value: "Doxycycline" },
    { label: "Bupropion", value: "Bupropion" },
    { label: "Escitalopram", value: "Escitalopram" },
    { label: "Citalopram", value: "Citalopram" },
    { label: "Propranolol", value: "Propranolol" },
    { label: "Pantoprazole", value: "Pantoprazole" },
    { label: "Ciprofloxacin", value: "Ciprofloxacin" },
    { label: "Clindamycin", value: "Clindamycin" },
    { label: "Hydrocodone", value: "Hydrocodone" },
    { label: "Oxycodone", value: "Oxycodone" },
    { label: "Insulin", value: "Insulin" },
    { label: "Fluoxetine", value: "Fluoxetine" },
    { label: "Venlafaxine", value: "Venlafaxine" },
    { label: "Duloxetine", value: "Duloxetine" },
    { label: "Cyclobenzaprine", value: "Cyclobenzaprine" },
    { label: "Methylphenidate", value: "Methylphenidate" },
    { label: "Amphetamine", value: "Amphetamine" },
    { label: "Alprazolam", value: "Alprazolam" },
    { label: "Diazepam", value: "Diazepam" },
    { label: "Lorazepam", value: "Lorazepam" },
    { label: "Sildenafil", value: "Sildenafil" },
    { label: "Tadalafil", value: "Tadalafil" },
    { label: "Valsartan", value: "Valsartan" },
    { label: "Olmesartan", value: "Olmesartan" },
    { label: "Ezetimibe", value: "Ezetimibe" },
    { label: "Rosuvastatin", value: "Rosuvastatin" },
    { label: "Pravastatin", value: "Pravastatin" },
    { label: "Spironolactone", value: "Spironolactone" },
    { label: "Finasteride", value: "Finasteride" },
    { label: "Tamsulosin", value: "Tamsulosin" },
    { label: "Sulfamethoxazole", value: "Sulfamethoxazole" },
    { label: "Trimethoprim", value: "Trimethoprim" },
    { label: "Cephalexin", value: "Cephalexin" },
    { label: "Azithromycin", value: "Azithromycin" },
    { label: "Levofloxacin", value: "Levofloxacin" },
    { label: "Metronidazole", value: "Metronidazole" },
    { label: "Acyclovir", value: "Acyclovir" },
    { label: "Valacyclovir", value: "Valacyclovir" },
    { label: "Montelukast", value: "Montelukast" },
    { label: "Glipizide", value: "Glipizide" },
    { label: "Glyburide", value: "Glyburide" },
    { label: "Pioglitazone", value: "Pioglitazone" },
    { label: "Sitagliptin", value: "Sitagliptin" },
    { label: "Liraglutide", value: "Liraglutide" },
    { label: "Exenatide", value: "Exenatide" },
    { label: "Canagliflozin", value: "Canagliflozin" },
    { label: "Dapagliflozin", value: "Dapagliflozin" },
    { label: "Empagliflozin", value: "Empagliflozin" },
    { label: "Saxagliptin", value: "Saxagliptin" },
    { label: "Linagliptin", value: "Linagliptin" },
    { label: "Alogliptin", value: "Alogliptin" },
    { label: "Sumatriptan", value: "Sumatriptan" },
    { label: "Rizatriptan", value: "Rizatriptan" },
    { label: "Zolmitriptan", value: "Zolmitriptan" },
    { label: "Eletriptan", value: "Eletriptan" },
    { label: "Naratriptan", value: "Naratriptan" },
    { label: "Frovatriptan", value: "Frovatriptan" },
    { label: "Almotriptan", value: "Almotriptan" },
    { label: "Erenumab", value: "Erenumab" },
    { label: "Galcanezumab", value: "Galcanezumab" },
    { label: "Fremanezumab", value: "Fremanezumab" },
    { label: "Eptinezumab", value: "Eptinezumab" },
    { label: "Ergotamine", value: "Ergotamine" },
    { label: "Dihydroergotamine", value: "Dihydroergotamine" },
    { label: "Verapamil", value: "Verapamil" },
    { label: "Nimodipine", value: "Nimodipine" },
    { label: "Diltiazem", value: "Diltiazem" },
    { label: "Lamotrigine", value: "Lamotrigine" },
    { label: "Valproate", value: "Valproate" },
    { label: "Topiramate", value: "Topiramate" },
    { label: "Levetiracetam", value: "Levetiracetam" },
    { label: "Carbamazepine", value: "Carbamazepine" },
    { label: "Phenytoin", value: "Phenytoin" },
    { label: "Phenobarbital", value: "Phenobarbital" },
    { label: "Gabapentin", value: "Gabapentin" },
    { label: "Pregabalin", value: "Pregabalin" }
];
