/// <reference path="../pb_data/types.d.ts" />
migrate((db) => {
  const collection = new Collection({
    "id": "vjhtxr0q8ti3oyn",
    "created": "2024-06-07 14:42:54.470Z",
    "updated": "2024-06-07 14:42:54.470Z",
    "name": "perscriptions",
    "type": "base",
    "system": false,
    "schema": [
      {
        "system": false,
        "id": "ug9uiq3d",
        "name": "doctor",
        "type": "relation",
        "required": true,
        "presentable": false,
        "unique": false,
        "options": {
          "collectionId": "21v58r1grxoix8g",
          "cascadeDelete": false,
          "minSelect": null,
          "maxSelect": 1,
          "displayFields": null
        }
      },
      {
        "system": false,
        "id": "oekjwdbd",
        "name": "patient",
        "type": "relation",
        "required": true,
        "presentable": false,
        "unique": false,
        "options": {
          "collectionId": "mt6zn57p163l3ut",
          "cascadeDelete": false,
          "minSelect": null,
          "maxSelect": 1,
          "displayFields": null
        }
      },
      {
        "system": false,
        "id": "ybxm1ugf",
        "name": "medication",
        "type": "select",
        "required": true,
        "presentable": false,
        "unique": false,
        "options": {
          "maxSelect": 1,
          "values": [
            "Aspirin",
            "Ibuprofen",
            "Acetaminophen",
            "Amoxicillin",
            "Metformin",
            "Atorvastatin",
            "Lisinopril",
            "Albuterol",
            "Omeprazole",
            "Levothyroxine",
            "Metoprolol",
            "Amlodipine",
            "Simvastatin",
            "Hydrochlorothiazide",
            "Losartan",
            "Gabapentin",
            "Sertraline",
            "Fluticasone",
            "Prednisone",
            "Furosemide",
            "Montelukast",
            "Clopidogrel",
            "Warfarin",
            "Tramadol",
            "Trazodone",
            "Meloxicam",
            "Cetirizine",
            "Loratadine",
            "Diphenhydramine",
            "Zolpidem",
            "Ranitidine",
            "Famotidine",
            "Doxycycline",
            "Bupropion",
            "Escitalopram",
            "Citalopram",
            "Propranolol",
            "Pantoprazole",
            "Ciprofloxacin",
            "Clindamycin",
            "Hydrocodone",
            "Oxycodone",
            "Insulin",
            "Fluoxetine",
            "Venlafaxine",
            "Duloxetine",
            "Cyclobenzaprine",
            "Methylphenidate",
            "Amphetamine",
            "Alprazolam",
            "Diazepam",
            "Lorazepam",
            "Sildenafil",
            "Tadalafil",
            "Valsartan",
            "Olmesartan",
            "Ezetimibe",
            "Rosuvastatin",
            "Pravastatin",
            "Spironolactone",
            "Finasteride",
            "Tamsulosin",
            "Sulfamethoxazole",
            "Trimethoprim",
            "Cephalexin",
            "Azithromycin",
            "Levofloxacin",
            "Metronidazole",
            "Acyclovir",
            "Valacyclovir",
            "Montelukast",
            "Glipizide",
            "Glyburide",
            "Pioglitazone",
            "Sitagliptin",
            "Liraglutide",
            "Exenatide",
            "Canagliflozin",
            "Dapagliflozin",
            "Empagliflozin",
            "Saxagliptin",
            "Linagliptin",
            "Alogliptin",
            "Sumatriptan",
            "Rizatriptan",
            "Zolmitriptan",
            "Eletriptan",
            "Naratriptan",
            "Frovatriptan",
            "Almotriptan",
            "Erenumab",
            "Galcanezumab",
            "Fremanezumab",
            "Eptinezumab",
            "Ergotamine",
            "Dihydroergotamine",
            "Verapamil",
            "Nimodipine",
            "Diltiazem",
            "Lamotrigine",
            "Valproate",
            "Topiramate",
            "Levetiracetam",
            "Carbamazepine",
            "Phenytoin",
            "Phenobarbital",
            "Gabapentin",
            "Pregabalin"
          ]
        }
      },
      {
        "system": false,
        "id": "hlkxsu83",
        "name": "dosage",
        "type": "number",
        "required": true,
        "presentable": false,
        "unique": false,
        "options": {
          "min": null,
          "max": null,
          "noDecimal": false
        }
      },
      {
        "system": false,
        "id": "49awvt9e",
        "name": "frequency",
        "type": "number",
        "required": true,
        "presentable": false,
        "unique": false,
        "options": {
          "min": null,
          "max": null,
          "noDecimal": false
        }
      },
      {
        "system": false,
        "id": "vsqnshlm",
        "name": "start",
        "type": "date",
        "required": true,
        "presentable": false,
        "unique": false,
        "options": {
          "min": "",
          "max": ""
        }
      },
      {
        "system": false,
        "id": "mtlxkxt9",
        "name": "end",
        "type": "date",
        "required": true,
        "presentable": false,
        "unique": false,
        "options": {
          "min": "",
          "max": ""
        }
      }
    ],
    "indexes": [],
    "listRule": "@request.auth.id = doctor.id || @request.auth.id = patient.id",
    "viewRule": "@request.auth.id = doctor.id || @request.auth.id = patient.id",
    "createRule": "@request.auth.id = doctor.id",
    "updateRule": "@request.auth.id = doctor.id",
    "deleteRule": "@request.auth.id = doctor.id",
    "options": {}
  });

  return Dao(db).saveCollection(collection);
}, (db) => {
  const dao = new Dao(db);
  const collection = dao.findCollectionByNameOrId("vjhtxr0q8ti3oyn");

  return dao.deleteCollection(collection);
})
